language: python
dist: xenial
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    env: UPLOAD=True
  - python: 3.7-dev
install:
- pip install .[test]
script: echo hello world
deploy:
  provider: pypi
  distributions: sdist
  user: mara-pypi-upload-account
  password:
    secure: KwOtUmjpoMV2yPx2UBti07+d2EDswdx894QusFaVe6sGt+/54YARNl+OkMRwGO+gTnr6/7jSOyob2rDQYv5lIB+MjgGqWKeovaqy1FUrDDgxEPwQ9U/pIHRGHkcs4fM96ccn5WGtRfePGA/IgxkL/joY2/hGhswPdu3U3Dd5SIo4Wme46vptzQ4N9RMgfmvLdKTp1OGekSJ6M7twqDErWmExBL1QfT4Qb2GTWLJkck5Bc/OvYGCQC/7qRBqI4v2QZ8x5AI+WuWDokhRZU9dmEr4zWzOL++PoEv5UwK59LCkVHFk08iWVmUeLJ5soUB2q79woHsafODes7vOKguc9inURilxNViEMdJz0GOsEzd0BXgySP08j/wuJqNJxPr4r4vNzT4UlqP/6F2M1Z3Fu4+5Qb19n/3TDH2fXWNn3hxBzkVYfPmNWOM3AdVt3r9c95RRDomtvQTIguwJ4FmJ8Yn70/oBN6JMgXDqqeMn6i0TMlgraxM85PU/iiosCwy+sy8KMG8yb8S5VI3sox9fbzqMatRem2cYf+9BvDwxcd9SWB5B7Ym7UZaETT7D+d0p9TuhhjPo8axjkjaX6/FJpEEVdRi/v+ex0JrGr97hN4WN514vUVHtLZLECrwllHIZ41B7YJltacUix/OOXkTgJKTHGatdaDe3bGJI74T1KZsE=
  on:
    tags: true
    branch: master
    repo: mara/mara-app
    condition: "$UPLOAD == True"
